<?php
/**
 * @file
 * Code for the UCLALIB Staff Directory feature.
 */

include_once 'uclalib_staff_directory.features.inc';

/**
 * Implements hook_theme().
 */
function uclalib_staff_directory_theme($existing, $type, $theme, $path) {
    return array(
        'node__staff_directory' => array(
            'render element' => 'content',
            'base hook' => 'node',
            'template' => 'node--staff_directory',
            'path' => drupal_get_path('module', 'uclalib_staff_directory') . '/templates',
        ),
        'views_view_summary_unformatted__staff_directory_a_z_list__attachment' => array(
            // 'render element' => 'content',
            'base hook' => 'views_view_summary_unformatted',
            'template' => 'views-view-summary-unformatted--staff-directory-a-z-list--attachment',
            'path' => drupal_get_path('module', 'uclalib_staff_directory') . '/templates',
        ),

    );
}
/**
 * Implements hook_preprocess_HOOK().
 */
function uclalib_staff_directory_preprocess_views_view_summary_unformatted (&$variables) {
    if ($variables['view']->name == 'staff_directory_a_z_list' && $variables['view']->current_display == 'panel_pane_1') {
        // suggest using a template that adds an "All" link to the bookplates glossary display
        $variables['theme_hook_suggestions'][] = 'views_view_summary_unformatted__staff_directory_a_z_lists__attachment';
    }
}


