<?php
/**
 * @file
 * Code for the UCLALIB Bookplates feature.
 */

include_once 'uclalib_bookplates.features.inc';


/**
 * Implements hook_ctools_plugin_directory()
 */
/*function uclalib_staff_profile_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}*/
/**
 * Implements hook_entity_info_alter(). see: http://www.webwash.net/tutorials/3-easy-ways-create-view-modes-drupal-7
 */
function uclalib_bookplates_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['landing_page'] = array(
    'label' => t('Landing Page'),
    'custom settings' => TRUE,
  );
}
/**
 * Implements hook_preprocess_node().
 */
function uclalib_bookplates_preprocess_node(&$variables) {
  if($variables['view_mode'] == 'landing_page') {
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__landing_page';
  }
}
/**
 * Implements hook_theme().
 */
function uclalib_bookplates_theme($existing, $type, $theme, $path) {
  return array(
    'node__bookplates' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--bookplates',
      'path' => drupal_get_path('module', 'uclalib_bookplates') . '/templates',
    ),
  );
}
?>

