<?php

/**
 * @file
 * Adds a panel pane style for collapsible regions and panes, on mobile devices.
 */

/*
 * Implements hook_ctools_plugin_directory().
 */
function panels_style_mobile_collapsible_ctools_plugin_directory($module, $plugin) {
  if (($module == 'panels' || $module == 'ctools') && $plugin == 'styles') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme()
 */
function panels_style_mobile_collapsible_theme() {
  return array(
    'panels_style_mobile_collapsible' => array(
      'variables' => array('handle' => NULL, 'content' => NULL, 'collapsed' => FALSE),
      'file' => 'plugins/styles/mobile_collapsible.inc',
    ),
    'mobile_collapsible' => array(
      'variables' => array('title' => NULL, 'content' => NULL, 'collapsed' => TRUE),
      'path' => drupal_get_path('module', 'panels_style_mobile_collapsible') . '/templates',
      'template' => 'mobile-collapsible',
    )
  );
}

