<?php
/**
 * @file
 * Code for the UCLALIB News feature.
 */

include_once 'uclalib_news.features.inc';


/**
 * Implements hook_FORMID_alter()
 *
 * Remove search label on news page.
 */
function uclalib_news_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == 'views-exposed-form-news-search-news-search') {
    $form['#info']['filter-search_api_views_fulltext']['label'] = '';
  }
}

/**
 * Implementation of hook_views_pre_build().
 */
function uclalib_news_views_pre_build(&$view) {
  if (array_key_exists('argument', $view->display_handler->handlers)) {
    if (array_key_exists('created_year', $view->display_handler->handlers['argument'])) {
      // set the created year's exception handler to the current date's year
      $view->display_handler->handlers['argument']['created_year']->options['exception']['value'] = date("Y");
    }
    if (array_key_exists('created_month', $view->display_handler->handlers['argument'])) {
      // set the created month's exception handler to the current date's month
      $view->display_handler->handlers['argument']['created_month']->options['exception']['value'] = date("m");
    }
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function uclalib_news_views_pre_render(&$view) {
  // De-dupe the blog Categoreiesand Tags before rendering
  if ($view->name == 'blog_terms') {
    $uniques = array();
    if ($view->current_display == 'blog_terms_cats_pane') {
      foreach ($view->result as $key => $value) {
        // remove repeat results from array and add unique values to array
        if (in_array($value->field_data_field_news_categories_field_news_categories_tid, $uniques)) {
          unset($view->result[$key]);
        } else {
          $uniques[] = $value->field_data_field_news_categories_field_news_categories_tid;
        }
      }
    }
    if ($view->current_display == 'blog_terms_tags_pane') {
      foreach ($view->result as $key => $value) {
        // remove repeat results from array and add unique values to array
        if (in_array($value->field_data_field_news_tags_field_news_tags_tid, $uniques)) {
          unset($view->result[$key]);
        } else {
          $uniques[] = $value->field_data_field_news_tags_field_news_tags_tid;
        }
      }
    }

    unset($uniques);
  }
}

/**
 * Implementation of hook_preprocess_views_view_summary().
 */
function uclalib_news_preprocess_views_view_summary(&$variables) {
  if ($variables['view']->name == 'blog_archives') {
    foreach ($variables['view']->result as $key => $row) {
      // renders the link in YYYY/MM format
      $variables['view']->result[$key]->url = arg(1).'/'.substr($row->created_year_month,0,4).'/'.substr($row->created_year_month,4,2);
    }
  }
}